### ISSUE TITLE
Out of date subreddit list

### ISSUE THREAD

**Issue by QuillOmega0** [Trellmor/BerryMotesApp#1]
The subreddits.json.gz is out of date and is missing some subreddits such as /r/BerryTubeCirclejerk for example.

Might want to recode it to pull the list from that's easier to add to, like a git file

**Comment by jamesmanning** [comment]
Rather than maintaining its own list, could it just pull the latest berrymotes json at emote sync time and grab the list of subreddits from its 'sr' properties (then grab unique elements)  At least until/unless the source BT data.py is maintained in a publicly-available location (simple added symlink on that machine to make it available via http?) instead of an outdated copy being on github (AFAICT).

The only gotcha is it'd lose subreddits when the BT scraper loses entire subreddits, but it could either union with the previous set of subreddits, or just not worry about it since that needs to get fixed in the BT scraper anyway.

Of course, you could still have it pull from a git file and then just some cron job that does the sr lookup from berrymotes.json and then does git commit ; git push or whatever. \ppshrug That'd probably be better if the berrymotes.json ends up moving locations at some point down the road, I guess.
